#pragma once

enum PeekType
{
	PEEK_DESKTOP_STREAM_START,
	PEEK_DESKTOP_STREAM_INPUT_EVENT,
	PEEK_DESKTOP_STREAM_SETTING_CHANGE,
	PEEK_DESKTOP_STREAM_STOP
};

enum MessageType
{
	MSGTYPE_AUTHENTICATION = 115
};